--- #YAML:1.0
name:               The-Net
version:            2009110702
abstract:           Use the Net to fetch your required modules.
author:
    - Abigail <cpan@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Fcntl:        0
    IO::File:     0
    LWP::Simple:  0
    perl:         5.006
    strict:       0
    warnings:     0
resources:
    repository:  git://github.com/Abigail/the--net.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:  []
test_requires:
    strict:    0
    warnings:  0
